image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: 8
      test_suite: "simple"
    - nodejs_version: 8
      test_suite: "installs"
    - nodejs_version: 6
      test_suite: "installs"

cache:
  - node_modules -> package.json

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: npm install -g bs-platform

build: off

skip_commits:
  files:
    - '**/*.md'

test_script:
  - node --version
  - npm --version
  - sh tasks/e2e-%test_suite%.sh

# TODO:
# USE_YARN=yes tasks/e2e... when
# https://github.com/yarnpkg/yarn/pull/3848 lands in a release
